name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Run a multi-line script
        run: |
          ls
          
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        env:
          EMAILFROM: ${{ secrets.EMAILFROM }}
          EMAILPASS: ${{ secrets.EMAILPASS }}
          EMAILTO: ${{ secrets.EMAILTO }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: ${{ secrets.PORT }}
          script: |
            pwd
            bash dir/setup.sh
            sleep 5
            go run dir/main.go
            rm -rf dir
     
     # - name: storing report
     #   uses: actions/upload-artifact@v3
     #   with:
     #     name: report
     #     path: report.png
